# SEGMENTING AND CLUSTERING NEIGHBORHOODS IN TORONTTO

In [1]:
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup
print('Imported Successfully .....')

Imported Successfully .....

# reading data from html

In [2]:
table = pd.read_html('https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M', header=0)

# Create the initial dataframe from the table
df = pd.DataFrame(data = table[0])

# Print the shape
print('The shape of the Raw Inital Datafram is: ', df.shape)

# Output the Head of the Table
df.head()

The shape of the Raw Inital Datafram is:  (180, 3)

  Postal code           Borough                Neighborhood
0         M1A      Not assigned                         NaN
1         M2A      Not assigned                         NaN
2         M3A        North York                   Parkwoods
3         M4A        North York            Victoria Village
4         M5A  Downtown Toronto  Regent Park / Harbourfront

# remove null or not assigned in table

In [3]:
df1=df[(df.Borough != 'Not assigned') & (df.Neighborhood != 'Not assigned')]

In [4]:

df1

,Postal code,Borough,Neighborhood
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,Regent Park / Harbourfront
5,M6A,North York,Lawrence Manor / Lawrence Heights
6,M7A,Downtown Toronto,Queen's Park / Ontario Provincial Government
...,...,...,...
160,M8X,Etobicoke,The Kingsway / Montgomery Road / Old Mill North
165,M4Y,Downtown Toronto,Church and Wellesley
168,M7Y,East Toronto,Business reply mail Processing CentrE
169,M8Y,Etobicoke,Old Mill South / King's Mill Park / Sunnylea /...
178,M8Z,Etobicoke,Mimico NW / The Queensway West / South of Bloo...

In [5]:

df1.reset_index(drop=True, inplace=True)

In [6]:
df1

,Postal code,Borough,Neighborhood
0,M3A,North York,Parkwoods
1,M4A,North York,Victoria Village
2,M5A,Downtown Toronto,Regent Park / Harbourfront
3,M6A,North York,Lawrence Manor / Lawrence Heights
4,M7A,Downtown Toronto,Queen's Park / Ontario Provincial Government
...,...,...,...
98,M8X,Etobicoke,The Kingsway / Montgomery Road / Old Mill North
99,M4Y,Downtown Toronto,Church and Wellesley
100,M7Y,East Toronto,Business reply mail Processing CentrE
101,M8Y,Etobicoke,Old Mill South / King's Mill Park / Sunnylea /...
102,M8Z,Etobicoke,Mimico NW / The Queensway West / South of Bloo...

In [7]:
df1.rename(columns={'Postal code':'PostalCode'},inplace=True)
part_01 = pd.DataFrame(df1.groupby(
    ['PostalCode', 'Borough'])['Neighborhood'].apply(
    lambda x: ', '.join(x))).reset_index()

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:4223: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(**kwargs)

In [8]:
part_01

    PostalCode      Borough                                       Neighborhood
0          M1B  Scarborough                                    Malvern / Rouge
1          M1C  Scarborough           Rouge Hill / Port Union / Highland Creek
2          M1E  Scarborough                Guildwood / Morningside / West Hill
3          M1G  Scarborough                                             Woburn
4          M1H  Scarborough                                          Cedarbrae
..         ...          ...                                                ...
98         M9N         York                                             Weston
99         M9P    Etobicoke                                          Westmount
100        M9R    Etobicoke  Kingsview Village / St. Phillips / Martin Grov...
101        M9V    Etobicoke  South Steeles / Silverstone / Humbergate / Jam...
102        M9W    Etobicoke                                          Northwest

[103 rows x 3 columns]

In [9]:
part_01.shape

(103, 3)